# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MendUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(579, 593)

        self.search_str = QtWidgets.QLineEdit(MainWindow)
        self.search_str.setGeometry(QtCore.QRect(70, 230, 301, 20))
        self.search_str.setObjectName("search_str")

        self.search_button = QtWidgets.QPushButton(MainWindow)
        self.search_button.setGeometry(QtCore.QRect(440, 230, 75, 23))
        self.search_button.setObjectName("search_button")
        self.search_button.setToolTip('Поиск')

        self.text_output = QtWidgets.QPlainTextEdit(MainWindow)
        self.text_output.setGeometry(QtCore.QRect(70, 300, 441, 261))
        self.text_output.setObjectName("text_output")
        self.text_output.setReadOnly(True)

        self.label = QtWidgets.QLabel(MainWindow)
        self.label.setGeometry(QtCore.QRect(70, 190, 111, 16))
        self.label.setObjectName("label")

        self.mend_pic = QtWidgets.QLabel(MainWindow)
        self.mend_pic.setGeometry(QtCore.QRect(235, 40, 141, 131))
        self.mend_pic.setObjectName("mend_pic")
        img = QtGui.QImage('mendeleev.jpg')
        img = img.scaled(141, 131, QtCore.Qt.KeepAspectRatio)
        pixmap = QtGui.QPixmap(img)
        self.mend_pic.setPixmap(pixmap)
        self.mend_pic.setToolTip('Д. И. Менделеев')

        self.spravka_button = QtWidgets.QPushButton(MainWindow)
        self.spravka_button.setGeometry(QtCore.QRect(440, 260, 75, 23))
        self.spravka_button.setObjectName("spravka_button")
        self.spravka_button.setToolTip('Справка')

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Интерактивная таблица Менделеева"))
        self.search_button.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Поиск</p></body></html>"))
        self.search_button.setText(_translate("MainWindow", "Поиск"))
        self.label.setText(_translate("MainWindow", "Найти:"))
        self.mend_pic.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Дмитрий Иванович Менделеев</p></body></html>"))
        self.mend_pic.setText(_translate("MainWindow", ""))
        self.spravka_button.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Справка</p></body></html>"))
        self.spravka_button.setText(_translate("MainWindow", "Справка"))
